### PR TITLE
groups: internal `any` on the item passed to getGroupForIndex

### PR DESCRIPTION
**Pull request by floor**
## Summary

The factory now types the whole config as `T`, so untyped plugins like `autosize()` fail. I’ll keep groups tight and leave `plugins` loose so existing call sites still typecheck.`ConfigInput` is fighting the type checker. I’ll keep the factory as `VListConfig<T>` and type the two test plugins that were still defaulting to `VListItem`.`getGroupForIndex` is now `(index: number, item?: T) => string` from the public config through layout, the async bridge, and `createVListFromConfig`.

**What changed**
- `GroupsConfig`, `GroupsPluginConfig`, `GroupLayout`, `AsyncBridgeConfig`, and `createGroupLayout` / `createAsyncGroupBridge` are generic in the item type. Accessors are `(index: number) => T | undefined`, not `any`.
- `createVListFromConfig` infers `T` from `items` or the template. An inline `groups.getGroupForIndex` gets `item?: T` (not `any`). A callback written for another item type is a type error, including when `groups` is optional on the input type.
- `test/types/groups.ts` locks that in: `IsAny` is false, a wrongly typed callback is rejected, optional `groups` is checked, and `createVListFromConfig<Row>` still fails (both type parameters are required).
- `[Unreleased]` in `CHANGELOG.md` records the two type-level breaks: the callback item is `T`, and factory/layout accessors no longer use `any`.

**Checks**
- `bun run typecheck` passed
- 214 groups/config unit tests passed

No commit, as requested.

_The agent’s own account of the change. The evidence is the diff and the engine verification below._

## Changes

```
CHANGELOG.md                       |  17 +++++
 src/config.ts                      |  23 ++++---
 src/plugins/groups/async-bridge.ts |  22 +++---
 src/plugins/groups/layout.ts       |  20 +++---
 src/plugins/groups/plugin.ts       |  12 ++--
 src/plugins/groups/sticky.ts       |   5 +-
 src/plugins/groups/types.ts        |   4 +-
 src/types.ts                       |   4 +-
 test/config/resolve.test.ts        |   4 +-
 test/types/groups.ts               | 136 +++++++++++++++++++++++++++++++++++++
 10 files changed, 203 insertions(+), 44 deletions(-)
```

## Verification

**Engine verification: PASSED**
Tree: `53e60a6b3133949fdb56132f751c9edce221406f` | Commit: `7a6f868f4e6d296692120f940be6f9866eee7057`
- Typecheck: exit 0 (5403ms)
- Tests and coverage threshold: exit 0 (21940ms)
- Build: exit 0 (1308ms)
- Bundle size: exit 0 (132ms)
- Heap growth: exit 0 (743ms)
- Migration notes: exit 0 (30ms)
- Browser suites: exit 0 (120557ms)

Refs FLO-167

**Task:** FLO-167 — groups: internal `any` on the item passed to getGroupForIndex

**Agent:** Grok 4.6 high fast · implementer

### CODE REVIEW

**Comment by floor** [comment]
## Claude Review (cycle 1)

**Committee Member:** Claude

**VOTE: REJECT**

The groups typing is correct, and both cycle-2 blockers are resolved. The new two-parameter `createVListFromConfig` signature introduces one regression in the `plugins` escape hatch. I reviewed `origin/agent/ce37ea39-…` (7a6f868f, one commit on top of `next` f690c3ad), exported with `git archive` to a temp dir.

## Verified

- `bun run typecheck` (all three tsconfigs) passes on the export.
- `bun test test/plugins/groups test/config` passes: 236 pass, 0 fail.
- I did not run the full suite or `--concurrent`. The diff changes no runtime code apart from two test call sites.

**1. Groups plumbing.**
- No `any` remains in `src/plugins/groups/*.ts`; I grepped non-comment lines.
- `plugin.ts:82-83` already typed `ctxGetItem` and `getLoadedItem` as `(index: number) => T | undefined`.
- `createGroupLayout(dataCount, config, getLoadedItem ?? ctxGetItem)` at `plugin.ts:808` now infers `T` with no cast, and so do both `layout.rebuild` calls at `:136` and `:687`.
- Every new generic has a `= VListItem` default, so `internals.ts:17-26` and unparameterised uses by plugin authors still compile.

**2. Cycle-2 blocker: inline callbacks no longer receive `any`.** I probed `createVListFromConfig` with `IsAny<typeof row>` in shapes `test/types/groups.ts` does not cover. All of these compile, and the inline callback's item is not `any` where that applies:
- `adapter` with no `items` and an annotated template: `T` is `Row`.
- No `items`, no adapter, un-annotated template: `T` is `VListItem`. `getItemAt` returns `VListItem | undefined`, the same result as the old `ConfigItem` fallback.
- Inline literal `items` with an un-annotated template: `T` is the widened object type, and `row!.category` type-checks.
- Heterogeneous literal `items`.
- A `VListConfig<Row> & { container }` variable: `getItemAt` returns `Row | undefined`.
- `groups: GroupsConfig<{ id: number }>` on a `Row` list is accepted, which is correct contravariance.
- A plain `GroupsConfig` variable that uses only the index.
- `groups` together with `selection`: `getGroupLayout()` and `select()` are both present on the result.

**3. Adapter delegation.** This compiles under the new signature: `function adapterLike<T extends VListItem>(config: VListConfig<T>, container): VList<T> { return createVListFromConfig({ ...config, container }); }`.

One pre-existing issue, not this PR's: all four adapter repos call `createVListFromConfig<T>(…)` (for example `vlist-react/src/index.ts:55`). That already fails against `next`'s single-`C` signature and still fails here. The adapters need a 3.x pass either way.

## Regression: `plugins` with default generics

On `next` the constraint was `C extends VListConfig<any>`, so `plugins` was effectively `VListPlugin<any>[]`. The PR's parameter type `VListConfig<T> & C` checks every element against `VListPlugin<T>` at `src/config.ts:117`. `PluginContext<T>` is invariant through `Emitter<VListEvents<T>>`, so a default-generic plugin is rejected.

The CHANGELOG states this as a rule ("`autosize<Row>()`, not a default `autosize()`"). The actual behaviour depends on how the template is written:

```ts
const tplRow = (r: Row): string => r.name;
// PR: error TS2375; next: compiles
createVListFromConfig({ container, items: rows, item: { estimatedHeight: 40, template: tplRow }, plugins: [autosize()] });
// PR: compiles; next: compiles
createVListFromConfig({ container, items: rows, item: { estimatedHeight: 40, template: (r: Row) => r.name }, plugins: [autosize()] });
// PR: compiles; this is the core path
createVList({ container, items: rows, item: { estimatedHeight: 40, template: tplRow } }, [autosize()]);
```

- **Trigger.** When the template is an inline arrow, the plugin's `T` is inferred to match the list's. When the template is an identifier, the plugin falls back to its default `VListItem`. The spread form `createVListFromConfig({ ...base, plugins: [selection()] })`, which is the pattern in `test/types/config.ts`, also errors.
- **Failure mode.** The user sees a nine-line invariance trace ending in "Property 'name' is missing in type 'VListItem'". It points at `emitter`, not at the fix.
- **Stricter than core.** The same call through `createVList` compiles. `createVListFromConfig`, the path every adapter goes through, is now stricter than the core. That reverses the direction of the CHANGELOG entry at `:248` ("an adapter list and a core list built from the same options did not behave the same").
- **No test pins it.** `test/types/groups.ts` has no `plugins` case. The only evidence is the two edited call sites in `test/config/resolve.test.ts`. Both use an identifier template, so they capture only the failing form.
- **Out of scope.** The finding is titled "internal `any` on groups" and its brief says "No behaviour change". This break is a side-effect of fixing inline inference, not something the task required.
- **One fix I tried that does not work.** `plugins?: VListPlugin<NoInfer<T>>[]` produces the same errors, so this is not a one-line fix.

**BLOCKER: `createVListFromConfig` must not reject default-generic escape-hatch plugins (`plugins: [autosize()]`, `[selection()]`) based on how the template is written.** Resolve it one of two ways:
- (a) Restore `next`'s acceptance, so the `plugins` slot is not checked invariantly against the inferred `T`. Core's `readonly VListPlugin<T, any>[]` at `src/core/create.ts:218` with `const P` is the working precedent. Pin it with positive cases in `test/types/`, covering both an identifier template and the `{ ...base, plugins }` spread.
- (b) Keep the stricter check. Then make it uniform or document the exact rule, add `@ts-expect-error` and positive cases to `test/types/` for both template forms, and add a **Breaking** line in the CHANGELOG. It currently sits under "Changed", in the last sentence of the second bullet.

I prefer (a), because it keeps this PR to its stated scope.

## Non-blocking

- The `createVListFromConfig` JSDoc says `createVListFromConfig<Row>` "does not compile (TypeScript requires both parameters)". That is true, and the last case in `test/types/groups.ts` pins it. The error a user sees is "Expected 2 type arguments", which is less self-explanatory than before. A one-line `@example` showing a typed config would help.
- `ConfigItem<C>` is no longer used by `createVListFromConfig` but is still exported and documented as the mechanism. Check that its JSDoc and the claim in `test/types/config.ts` still describe reality, or note that it is now advisory.
- Owner concern, not a blocker: `GroupsConfig<T>` makes a formerly `any` public callback strict. That is the right call for 3.0, and the CHANGELOG covers it adequately.

## Dimensions

- **Correctness:** the groups path is correct. The `plugins` path regresses, as above.
- **Architecture:** generics with defaults fit the existing `VListPlugin<T, M>` conventions.
- **Performance:** types only, no runtime change.
- **Maintainability:** the two-parameter intersection signature (`VListConfig<T> & C`) is subtler than the single-`C` one. The `plugins` regression is a direct consequence of it, so its type tests need to cover every field that carries `T`, not only `groups`.

**Vote:** REJECT

**Agent:** Claude Opus · committee member

**Comment by floor** [comment]
## Codex Review (cycle 1)

**Committee Member:** Codex

The change is sound. No blockers found.

The generic follows the actual data flow: `groups<T>()` passes a `GroupsConfig<T>` and a `T | undefined` accessor into `createGroupLayout`, and `getGroupLayout()` preserves that same `T` through `rebuild`. Keeping the callback’s item optional preserves the unloaded-item case without introducing runtime assumptions.

The factory signature is the highest-risk change because it affects all config-based lists. I checked the proposed signatures using an in-memory TypeScript compiler overlay, without modifying the repository. The existing config type tests and additional probes passed:

- Inline callbacks infer `Row`, including when `groups` precedes `items`.
- Template-only configs preserve the item type.
- Optional incompatible groups configs are rejected.
- Callbacks requiring additional fields absent from the list’s items are rejected.
- Group and selection methods remain available on the resulting list.

The migration cost is real but documented: previously accepted default-typed escape-hatch plugins may now require explicit item parameters, such as `autosize<Row>()`. That affects users without groups too. The changelog correctly identifies this broader consequence; it should remain prominent in the release notes.

There is no runtime performance improvement to claim. These changes erase during compilation and leave grouping, index conversion, scrolling, and DOM operations unchanged. Browser scroll-physics testing would add little evidence for this patch; compile-time compatibility tests are the relevant verification.

The supplied regression tests address the prior review’s substantive blockers: contextual `any`, incompatible callbacks, and optional `groups`. Adding a template-only groups inference case would strengthen coverage of the documented factory contract, but the compiler probe passed and this is not a blocker.

**VOTE: APPROVE**

**Vote:** APPROVE

**Agent:** Codex Local · committee member

**Comment by floor** [comment]
## 🗳️ Committee PR Review (cycle 1/3)
| Agent | Vote |
|-------|------|
| Claude | **REJECT** |
| Codex | **APPROVE** |
**Outcome: CHANGES REQUESTED**

### Blockers

**Claude:**
`createVListFromConfig` must not reject default-generic escape-hatch plugins (`plugins: [autosize()]`, `[selection()]`) based on how the template is written.** Resolve it one of two ways:
> Duration: 3m 16s
> Total cost: $1.9946

**Agent:** Floor Agents · engine

**Comment by floor** [comment]
## Claude Review (cycle 2)

**Committee Member:** Claude

I exported the PR head (`aaca7fb6`) and `next` (`f690c3ad`) to scratch directories and compiled probe files against both with `tsc -p tsconfig.types.json`. `bun run typecheck` passes on the PR. `bun test test/plugins/groups test/config` gives 236 pass, 0 fail. Every claim below was compiled unless I say otherwise.

## What is correct

- **Internal threading is type-only.** `layout.ts` (`buildGroups`, `createGroupLayout`, `rebuild`), `async-bridge.ts`, `sticky.ts`, `types.ts:116` and `plugin.ts` change no emitted code. They add nothing to the hot path and no allocations.
- **The cycle-2 blockers are resolved.** Inline `getGroupForIndex` callbacks receive the inferred item type, with `IsAny = false`, in four cases I probed:
  - `items` plus an un-annotated template
  - no `items` plus an annotated template
  - no `items` plus a declared `ItemConfig<Row>`
  - adapter-only with an un-annotated template. This last case is an improvement: `T` infers as `Row` from `adapter.read`, where `next` gives the wrong item type.
- **Codex's optional-`groups` case is covered and passes.**
- **The 3.x adapters still compile.** `vlist-react` `origin/next:src/index.ts:69` calls `createVListFromConfig({ ...configRef.current, container }) as UseVListInstance<C>` with a generic `C extends VListConfig<any>`. I probed that exact shape, plus a generic-`T` wrapper, and both compile.
- **The cycle-3 blocker is resolved.** `[autosize()]` and `[selection()]` are accepted for an identifier template and for a spread config.

## Blocking regression: the item type depends on how the template is written

The old signature computed the item with `ConfigItem<C>`, which takes `items` first and the template second (`src/config.ts:289-293`). The new signature at `src/config.ts:311-314` infers `T` from every position in `VListConfig<T> & C` at once. When an inline template is annotated for a supertype of the items, the template's annotation wins over `items`:

```ts
declare const items: Row[];   // Row = { id; name; category }
const b = createVListFromConfig({
  container, items,
  item: { height: 40, template: (r: VListItem, i: number) => String(r.id) + i },
  selection: { mode: "single" },
});
b.getSelectedItems().map((r) => r.name);
// PR:   TS2339 — 'name' does not exist on type 'VListItem'
// next: compiles, item is Row
```

- **Verified result.** With template `(r: { id: number }) => …`, `getItemAt(0)` is `{ id: number } | undefined` on the PR and `Row | undefined` on `next`.
- **It breaks the feature this PR adds.** The same config with `groups: { getGroupForIndex: (_i, row) => row!.category }` fails with "Property 'category' does not exist on type 'VListItem'".
- **It depends on the spelling of the template.** Hoist the identical template to `const tpl = (r: VListItem): string => …` and the PR infers `Row` and accepts everything. This is the same defect class as the cycle-3 blocker, and the same config compiles or fails depending on whether the template is inline.
- **Core and adapters now disagree.** `ConfigItem` is still exported, and the adapters use it for `UseVListInstance<C>`. For this config the adapter reports `Row` while the core infers `{ id: number }`, and the `as UseVListInstance<C>` cast hides the difference.
- **Who is affected.** Templates typed against a base shape are an ordinary pattern, for example a shared `(item: VListItem) => …` renderer or a `BaseRow` renderer reused across lists.
- **It is undocumented.** The CHANGELOG does not mention it and no test pins it.

**BLOCKER: `createVListFromConfig` must give `items` priority over the template when inferring the item, as `ConfigItem` does on `next`. A config with `items: Row[]` and an inline template annotated for a supertype must produce `VList<Row>` and a `Row`-typed `getGroupForIndex` item, the same as when that template is a named constant. Add both spellings, inline and identifier, to `test/types/`, asserting `getItemAt` returns `Row | undefined` and that an inline `groups` callback reads `row.category`.**

I tried one fix: `VListConfig<NoInfer<T>> & { items?: T[] } & C`. It breaks the no-`items` cases in `test/types/config.ts:47`, so the fix is not a one-liner. One direction to try is keeping `ConfigItem<C>` as the single source of `T` and contextually typing only `groups` from it. If no signature can satisfy both requirements, the owner should decide which one yields. The current state regresses one silently.

## Secondary: the documentation overstates `plugins` parity with `createVList`

The CHANGELOG says "Escape-hatch `plugins` stay as loose as on `createVList`", and the JSDoc at `src/config.ts:117-118` says default-generic plugins are "accepted the same way as `createVList`'s plugin list". Compiled check:

```ts
const other = groups<{ id: number; nope: string }>({ … r!.nope … });
createVList({ container, items, item }, [other]);              // TS2375 — rejected
createVListFromConfig({ container, items, item, plugins: [other] }); // accepted
```

- **The config field is looser than `createVList`.** `VListPlugin<any, any>[]` accepts a plugin typed for the wrong item. That is the exact hole this PR closes on the `groups` field, and it stays open one field over.
- **Tightening is not available.** I tried `VListPlugin<NoInfer<T>, any>[]`. It rejects `autosize()`, because `VListPlugin` is invariant through `PluginContext.emitter`, and `test/types/config.ts:92` fails. So `any` is a defensible way to resolve the cycle-3 blocker. The text describing it is what is wrong.

**BLOCKER: correct the CHANGELOG entry and the `plugins` JSDoc. The field is looser than `createVList` — a plugin explicitly typed for a different item, such as `groups<Other>()`, is accepted with no check. Say so, and add a `test/types/` case pinning the behaviour so it is a recorded decision.**

## Concern for the owner (non-blocking)

`plugins?: VListPlugin<any, any>[]` adds an `any` to a public type, against the "No `any`. Zero tolerance" rule in CLAUDE.md. The only precedent is the methods slot, `VListPlugin<T, any>` at `src/core/create.ts:218`, not the item slot. Because of the invariance above I see no alternative. This needs an explicit owner decision recorded on the PR.

## Notes

- **Readonly items are not a regression.** `readonly`/`as const` `items` are rejected with TS4104 on both the PR and `next`. This is out of scope.
- **The partial-type-argument trap stays closed.** `createVListFromConfig<Row>(…)` errors and the test covers it. The released 2.x adapters call it that way, but `next` already rejects that call, so this PR does not change it.
- **The CHANGELOG is otherwise accurate.** It records the `GroupsConfig<T>` break and the `GroupLayout.rebuild` signature change.

**VOTE: REJECT**

**Issues to resolve**

1. **BLOCKER:** `items` must outrank an inline supertype-annotated template in item inference. Today the PR infers `{ id: number }` or `VListItem` where `next` infers `Row`, the result depends on whether the template is inline or a named constant, and the `groups` callback is falsely rejected. Add both spellings to `test/types/`.
2. **BLOCKER:** fix the false "as loose as `createVList`" claim in the CHANGELOG and the `plugins` JSDoc, and pin the actual behaviour with a type test.

The scratch exports remain in `/tmp/vlist-pr-ce37` and `/tmp/vlist-next-f690` because `trash` was refused on `/tmp`. The repository working tree is untouched.

**Vote:** REJECT

**Agent:** Claude Opus · committee member

**Comment by floor** [comment]
## Codex Review (cycle 2)

**Committee Member:** Codex

**BLOCKER: Preserve item inference from `items` when the template accepts a broader item type.**

The new `createVListFromConfig` signature allows the template parameter to widen `T` to `VListItem`, even when `items` is explicitly `Row[]`. Previously, `ConfigItem<C>` gave `items` precedence.

Concrete regression:

```ts
interface Row {
  id: number;
  name: string;
  category: string;
}

declare const items: Row[];
declare const container: HTMLElement;

const list = createVListFromConfig({
  container,
  items,
  item: {
    height: 40,
    template: (row: VListItem) => String(row.id),
  },
});

const first: Row | undefined = list.getItemAt(0);
```

This compiles against the current repository but fails with the proposed signature: `getItemAt()` returns `VListItem | undefined`. Adding an inline groups callback that reads `row!.category` also fails because its item becomes `VListItem`.

A reusable template that renders only IDs is valid for richer items. Its narrower requirements should not erase the list’s data type. This affects factory users without groups, expanding the migration impact beyond the intended callback tightening.

Required resolution:

- Preserve the existing precedence of the declared `items` element type while retaining contextual typing and optional-groups validation.
- Add regression coverage for `Row[]` paired with a template accepting `VListItem`, asserting both the returned item type and the inline groups callback type.

The internal generic propagation is otherwise a sound incremental change. Keeping `item` optional preserves unloaded-item handling; these type-only changes introduce no scroll, layout, allocation, or browser behavior changes and provide no runtime speed improvement.

I reproduced the inference regression using the repository’s TypeScript configuration in isolated copies; the workspace remains unchanged. Existing type tests pass with the production changes, but miss this case. The default-generic plugin compatibility cases also passed the additional probes.

**VOTE: REJECT**

**Vote:** REJECT

**Agent:** Codex Local · committee member

**Comment by floor** [comment]
## 🗳️ Committee PR Review (cycle 2/3)
| Agent | Vote |
|-------|------|
| Claude | **REJECT** |
| Codex | **REJECT** |
**Outcome: CHANGES REQUESTED**

### Blockers

**Claude:**
`createVListFromConfig` must give `items` priority over the template when inferring the item, as `ConfigItem` does on `next`. A config with `items: Row[]` and an inline template annotated for a supertype must produce `VList<Row>` and a `Row`-typed `getGroupForIndex` item, the same as when that template is a named constant. Add both spellings, inline and identifier, to `test/types/`, asserting `getItemAt` returns `Row | undefined` and that an inline `groups` callback reads `row.category`.
correct the CHANGELOG entry and the `plugins` JSDoc. The field is looser than `createVList` — a plugin explicitly typed for a different item, such as `groups<Other>()`, is accepted with no check. Say so, and add a `test/types/` case pinning the behaviour so it is a recorded decision.

**Codex:**
Preserve item inference from `items` when the template accepts a broader item type.
> Duration: 3m 32s
> Total cost: $2.0596

**Agent:** Floor Agents · engine

**Comment by floor** [comment]
## Claude Review (cycle 3)

**Committee Member:** Claude

## Method

I exported the PR branch `origin/agent/ce37ea39-…` (tip 44f9a664, merge-base `next` f690c3ad) and `origin/next` to two temp directories and ran the toolchain against both. On the PR export, `bun run typecheck` (all three tsconfigs) passes. `bun test test/plugins/groups test/config` gives 236 pass, 0 fail. `bun run build` passes, with base still 9.9 kB gzipped. I did not run the full suite or `--concurrent`, since the `src/` diff changes types only. I then compiled 17 type-level probe cases against both exports to separate regressions from existing behaviour.

## 1. Correctness

**The cycle-2 blockers are resolved.** Both spellings I asked for are in `test/types/groups.ts`: `fromIdentifier` and `fromInline` both yield `getItemAt(0): Row | undefined`, and the inline `groups` callback reads `row!.category`. The mechanism holds up:

- Overload 1 (`src/config.ts:317-320`) fires when `items` is present. `CheckedConfig<T>` wraps the template parameter in `NoInfer<T>`, so `items` is the only inference site for `T`. The template is then checked against `T` contravariantly, not inferred from.
- Overload 2 (`src/config.ts:321-324`) handles configs without `items`, where the template or a callback annotation supplies `T`.

**Probe results, PR vs `next`:**

| Case | `next` | PR |
|---|---|---|
| `items` + un-annotated inline template: is `r` `any`? | `any` | `Row` |
| `adapter` + un-annotated template | `any` | typed |
| `adapter` + annotated template + inline groups callback | `any` | `Row` |
| Wrong-typed groups callback, no `items` (overload 2) | accepted | rejected |
| `items` + template for an unrelated type | rejected | rejected (both overloads fail) |
| `items: Row[]` + `item: ItemConfig<Entity>` variable + inline groups reading `category` | n/a | compiles, `Row` |
| Union-typed items, `factory: createVList`, `VListConfig<Row>`-typed variable | — | compile |
| Generic adapter-shaped wrapper `<T extends VListItem>(config: VListConfig<T>, el) => createVListFromConfig({ ...config, container: el })` returning `VList<T>` | — | compiles |
| Named callback typed for a supertype (`e?: Entity`) with `items: Row[]` | — | accepted (correct contravariance) |
| `items: Row[] \| undefined` | rejected | rejected |
| `as const` tuple for `items` | rejected | rejected |

The last two rows fail identically on `next`. They come from `exactOptionalPropertyTypes` and the mutable `items: T[]` on the base config, so they are pre-existing and not regressions.

The PR improves on its stated scope: un-annotated templates stop being `any` on the config path. That leak exists on `next` today through the `VListConfig<any>` constraint.

**Internal threading is complete.** In `plugin.ts`, `ctxGetItem` and `getLoadedItem` were already `(index) => T | undefined` (lines 82-83). Every `createGroupLayout` / `layout.rebuild` call site (136, 687, 808, 858) passes a `T`-typed accessor into the now-generic signatures, with no casts added. `buildGroups<T>` is inferred at both call sites. `createStickyHeader<T>` and `createGroupedSizeFn<T>` only needed the parameter widened. There is no runtime diff in `src/`, so hot-path and allocation concerns do not apply.

**The partial-type-argument trap stays closed.** `createVListFromConfig<Row>` is now an arity error, and the last test case pins it. All four adapter repos currently call `createVListFromConfig<T>(…)` (`vlist-react/src/index.ts:55`, vue `:63`, svelte `:54`, solidjs `:61`). That spelling is already a compile error against `next`'s single-`C` signature, so this PR does not newly break them. The adapter-shaped wrapper probe shows the argument-free spelling works for generic `T`.

## 2. Architecture fit

- `plugins?: VListPlugin<any, any>[]` (`src/config.ts:120`) is the only `any` this PR adds, against a "zero tolerance" rule. I accept it for three reasons:
  - It is the recorded decision from the previous cycle; the JSDoc, the CHANGELOG, and a `test/types/config.ts` case all pin it.
  - `src/core/create.ts:218` (`VListPlugin<T, any>[]`) and `src/core/types.ts:300` set precedent for `any` in plugin-variance positions.
  - On `next` the effective type through the `VListConfig<any>` constraint was already `VListPlugin<any>[]`.
- The `any` on the methods slot is necessary. `VListPlugin<T>` defaults `M` and would reject `search<Row>()`'s methods under invariance.
- The generic defaults (`= VListItem`) on `GroupsConfig`, `GroupLayout`, `GroupsMethods`, `AsyncGroupBridge` and `AsyncBridgeConfig` keep every non-generic reference source-compatible. That includes the `src/internals.ts` re-exports and `selection/plugin.ts:111`'s structural read of `getGroupLayout`.

## 3. Performance

Nothing to review. Emitted JS is unchanged, and the build and size output are identical.

## 4. Maintainability

Two overloads plus `CheckedConfig` is more machinery than `next`'s one-liner. It buys three things the simpler forms could not deliver together: `items` wins, inline callbacks are typed, and optional-`groups` inputs are checked. Cycles 1–2 demonstrated that. The implementation signature duplicating overload 2 is standard. The JSDoc now describes what the code does.

## 5. Gaps (non-blocking)

1. **`NoInfer` raises the consumer TypeScript floor for `vlist/config` to 5.4.** `const` type parameters already required 5.0. `typescript` is only a devDependency (`package.json:106`, `^5.0.0`), so nothing declared is violated. However, consumers on 5.0–5.3 with `skipLibCheck: false` will see `Cannot find name 'NoInfer'`. Add a line to the CHANGELOG entry or note the supported TS floor in the docs. I could not find `createVListFromConfig` in the temp build's emitted `.d.ts`, so the declaration shape is unconfirmed; typecheck is what I verified.
2. **Error ergonomics.** A mismatch now reports `TS2769 No overload matches this call` with both overload bodies expanded, about 10 lines, and the error lands on the call rather than the offending property. In my `items` + unrelated-template probe, a `@ts-expect-error` placed on the `item:` line went unused because the error moved to the call expression. This costs existing users who have positional `@ts-expect-error` directives. It is acceptable, but it is a user-visible change the CHANGELOG does not mention.
3. **No `test/types/` case for `createAsyncGroupBridge<T>`.** The `onItemsLoaded(items: T[])` and `insertAt(_, item: T)` changes are named in the CHANGELOG, but only `createGroupLayout` / `rebuild` have a negative case. The bridge has no in-repo caller (`plugin.ts` does not import it), so the type test would be its only guard.
4. **Un-annotated `groups({ getGroupForIndex: (_i, row) => row.category })` inside a `createVList` plugin array now fails.** It infers `T = VListItem`, so `row.category` is an error where it compiled under `any`. The CHANGELOG covers this with "need to name the item or use `groups<Row>(…)`". The vlist.io docs and examples in the separate repo likely contain this exact spelling and should be swept before 3.0.0.
5. **Commit subjects on the branch** (`groups: internal \`any\` on…`) are not Conventional Commits. Use `fix(groups): …` or `refactor(groups): …` for the squash title.
6. **Concern for the owner, not the implementer.** `VListConfig<Row>['plugins']` is now a public field typed with `any`, visible to every adapter user. If the intent is only to tolerate default-generic plugins, a later pass could narrow it to `VListPlugin<T, any> | VListPlugin<VListItem, any>`. Verify first that this does not re-break `[autosize()]`. It does not belong in this PR.

## Conditions

- Mention the TS ≥ 5.4 floor for `vlist/config` types in the CHANGELOG entry (gap 1).
- Add a `createAsyncGroupBridge<Row>` case to `test/types/groups.ts` (gap 3). This can be a follow-up.
- Use a Conventional Commit title at merge (gap 5).

I have no blockers.

**VOTE: APPROVE**

**Vote:** APPROVE

**Agent:** Claude Opus · committee member

**Comment by floor** [comment]
## Codex Review (cycle 3)

**Committee Member:** Codex

The internal generic propagation is appropriate and incremental. It changes no executable grouping, scrolling, or DOM logic; no runtime performance improvement is expected. Keeping `item` optional preserves the unloaded-item case.

**BLOCKER: Preserve inference from `items` when the grouping callback accepts a broader item type.**

The factory overloads still violate the settled `items`-first requirement. `CheckedConfig<T>` blocks inference from the template, but other callback annotations can still widen `T`.

I reproduced this using the repository’s TypeScript compiler against the proposed signatures in a temporary copy:

```ts
interface Entity {
  id: number;
  name: string;
}
interface Row extends Entity {
  category: string;
}

declare const items: Row[];
declare const container: HTMLElement;

const list = createVListFromConfig({
  container,
  items,
  item: {
    height: 40,
    template: (entity: Entity) => entity.name,
  },
  groups: {
    getGroupForIndex: (_index, entity?: Entity) =>
      entity?.name ?? "",
  },
});

const row: Row | undefined = list.getItemAt(0);
// TS2322: Entity | undefined is not assignable to Row | undefined.
```

Both callbacks safely accept every `Row`. Existing `ConfigItem<C>` derives `Row` from `items`, but the proposed factory returns `VList<Entity>`. Consequently, existing callers lose access to `category`; the inferred list also permits inserting an `Entity` without that field.

The failure occurs with both inline and named templates. Moving the grouping configuration into a variable typed `GroupsConfig<Entity>` preserves `Row`, making the result depend on how an equivalent configuration is written.

The fix must make required `items` authoritative while checking callbacks against that item type. Add regression cases covering broader grouping callbacks, inline and named templates, and a named grouping configuration. Assert the returned item is `Row | undefined` and that inserting an item without `category` is rejected.

The documented escape-hatch plugin looseness is a recorded decision, so I am not reopening it as a blocker. The remaining issue is in the checked convenience configuration itself.

**VOTE: REJECT**

**Vote:** REJECT

**Agent:** Codex Local · committee member

**Comment by floor** [comment]
## 🗳️ Committee PR Review (cycle 3/3)
| Agent | Vote |
|-------|------|
| Claude | **APPROVE** |
| Codex | **REJECT** |
**Outcome: CHANGES REQUESTED**

### Blockers

**Codex:**
Preserve inference from `items` when the grouping callback accepts a broader item type.

### Stood through a revision

- **Codex:** Preserve inference from `items` when the grouping callback accepts a broader item type.
  - before the revision: Preserve item inference from `items` when the template accepts a broader item type.

The implementer revised the change and the same blocker came back, so the review loop stops here instead of spending another cycle on it.
A person decides: settle the point in a comment on the issue (reviewers read the discussion and treat a recorded decision as settled), then `floor-agents review --issue <id>` seats the committee again on this pull request; or change the brief and `run --issue <id> --retry`; or close the pull request.
> Duration: 3m 13s
> Total cost: $2.0696

**Agent:** Floor Agents · engine

**Comment by floor** [comment]
Superseded by #265, which carries this work and fixes Codex's last blocker: with `items` given it is now the only place the item type is inferred from, so a template or a grouping callback annotated for a supertype is accepted without widening the list. The three spellings from the review are regression cases in `test/types/groups.ts`.

**Agent:** Claude Fable 5.1 · team lead
